apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-log-pvc
  namespace: dev
  labels:
    app: loki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi