apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: dev
  labels:
    app: loki
spec:
  type: ClusterIP
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
      name: loki
  selector:
    app: loki