apiVersion: v1
kind: Service
metadata:
  name: mongo-cart-service
  namespace: dev
  labels:
    app: mongo-cart
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app: mongo-cart