apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-service
  labels:
    app.kubernetes.io/name: warehouse
    app.kubernetes.io/instance: warehouse-service # Using service name as instance name
    app.kubernetes.io/managed-by: manual # Indicating manual management
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: warehouse
      app.kubernetes.io/instance: warehouse-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: warehouse
        app.kubernetes.io/instance: warehouse-service
    spec:
      containers:
        - name: warehouse
          image: "nourwk/warehouse:v1.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://psql-warehouse-service:5435/$(WAREHOUSE_DB_NAME)
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.PostgreSQLDialect
            - name: SPRING_RABBITMQ_HOST
              value: my-rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /api
            - name: SERVER_PORT
              value: "8085"
            - name: SPRING_DATA_REDIS_HOST
              value: redis-service
          envFrom:
            - secretRef:
                name: warehouse-secrets
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8085
            initialDelaySeconds: 300
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8085
            initialDelaySeconds: 300
            periodSeconds: 30