apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-service
  labels:
    app.kubernetes.io/name: warehouse
    app.kubernetes.io/instance: warehouse-service # Using service name as instance name
    app.kubernetes.io/managed-by: manual # Indicating manual management
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: warehouse
      app.kubernetes.io/instance: warehouse-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: warehouse
        app.kubernetes.io/instance: warehouse-service
    spec:
      containers:
        - name: warehouse
          image: "nourwk/warehouse:v1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://psql-db:5432/warehouseDB
          envFrom:
            - secretRef:
                name: warehouse-secrets
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8085
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8085
            initialDelaySeconds: 300
            periodSeconds: 5