apiVersion: v1
kind: Service
metadata:
  name: warehouse-service
  labels:
    app.kubernetes.io/name: warehouse
    app.kubernetes.io/instance: warehouse-service # Using service name as instance name
    app.kubernetes.io/managed-by: manual # Indicating manual management
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: warehouse
    app.kubernetes.io/instance: warehouse-service