apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-service
  labels:
    app.kubernetes.io/name: erp
    app.kubernetes.io/instance: erp-service # Using service name as instance name
    app.kubernetes.io/managed-by: manual # Indicating manual management
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: erp
      app.kubernetes.io/instance: erp-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: erp
        app.kubernetes.io/instance: erp-service
    spec:
      containers:
        - name: erp
          image: "nourwk/erp:v1.0.6"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://psql-erp-service:5433/$(ERP_DB_NAME)
            - name: SPRING_RABBITMQ_HOST
              value: my-rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /api
            - name: SERVER_PORT
              value: "8083"
          envFrom:
            - secretRef:
                name: erp-secrets
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8083
            initialDelaySeconds: 300
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8083
            initialDelaySeconds: 300
            periodSeconds: 30