apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-log-pvc
  namespace: dev
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi