apiVersion: v1
kind: Service
metadata:
  name: psql-auth-service
  namespace: dev
  labels:
    app: psql-auth
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: psql-auth