apiVersion: apps/v1
kind: Deployment
metadata:
  name: courier-service
  labels:
    app.kubernetes.io/name: courier
    app.kubernetes.io/instance: courier-service # Using service name as instance name
    app.kubernetes.io/managed-by: manual # Indicating manual management
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: courier
      app.kubernetes.io/instance: courier-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: courier
        app.kubernetes.io/instance: courier-service
    spec:
      containers:
        - name: courier
          image: "nourwk/courier:v1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo-courier-service:27018/$(COURIER_DB_NAME)
            - name: SPRING_RABBITMQ_HOST
              value: my-rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /api
            - name: SERVER_PORT
              value: "8082"
          envFrom:
            - secretRef:
                name: courier-secrets
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8082
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8082
            initialDelaySeconds: 300
            periodSeconds: 5