apiVersion: v1
kind: Service
metadata:
  name: courier-service
  labels:
    app.kubernetes.io/name: courier
    app.kubernetes.io/instance: courier-service # Using service name as instance name
    app.kubernetes.io/managed-by: manual # Indicating manual management
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: courier
    app.kubernetes.io/instance: courier-service