apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-init-scripts
  namespace: dev
data:
  init-users-psql.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
      CREATE USER $AUTH_DB_USERNAME WITH PASSWORD '$AUTH_DB_PASSWORD';
      CREATE DATABASE $AUTH_DB_NAME OWNER $AUTH_DB_USERNAME;

      CREATE USER $ERP_DB_USERNAME WITH PASSWORD '$ERP_DB_PASSWORD';
      CREATE DATABASE $ERP_DB_NAME OWNER $ERP_DB_USERNAME;

      CREATE USER $ORDER_DB_USERNAME WITH PASSWORD '$ORDER_DB_PASSWORD';
      CREATE DATABASE $ORDER_DB_NAME OWNER $ORDER_DB_USERNAME;

      CREATE USER $WAREHOUSE_DB_USERNAME WITH PASSWORD '$WAREHOUSE_DB_PASSWORD';
      CREATE DATABASE $WAREHOUSE_DB_NAME OWNER $WAREHOUSE_DB_USERNAME;
    EOSQL