apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: dev
  labels:
    app: redisinsight
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
        - name: redisinsight
          image: redis/redisinsight:2.68
          ports:
            - containerPort: 5540
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 400Mi