apiVersion: v1
kind: Service
metadata:
  name: redisinsight
  namespace: dev
  labels:
    app: redisinsight
spec:
  type: ClusterIP
  ports:
    - port: 5540
      targetPort: 5540
      protocol: TCP
      name: redisinsight
  selector:
    app: redisinsight