apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: warehouse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Podzilla/infrastructure
    targetRevision: main
    path: environments/dev/warehouse
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true