apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: dev
  labels:
    app: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:3.5.0
          command: ["-config.file=/etc/promtail/promtail-config.yaml"]
          ports:
            - containerPort: 9080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail/promtail-config.yaml
              subPath: promtail-config.yaml
            - name: logs
              mountPath: /logs
      volumes:
        - name: promtail-config
          hostPath:
            path: /absolute/path/to/promtail-config.yml
            type: File
        - name: logs
          hostPath:
            path: /absolute/path/to/logs
            type: Directory