apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: dev
  labels:
    app: promtail
spec:
  type: ClusterIP
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
      name: promtail
  selector:
    app: promtail