apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: api-gateway-service # Using service name as instance name
    app.kubernetes.io/managed-by: manual # Indicating manual management
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: api-gateway-service