
serviceName: api-gateway

replicaCount: 2

image:
  repository: nourwk/api-gateway
  tag: v1.0.0

service:
  port: 80
  type: ClusterIP
  healthUrl: /api/actuator/health

env:
  # basic routes
  - name: ROUTES_AUTH
    value: "http://auth-service:8086"
  - name: ROUTES_COURIER
    value: "http://courier-service:8082"
  - name: ROUTES_WAREHOUSE
    value: "http://warehouse-service:8085"
  - name: ROUTES_ERP
    value: "http://erp-service:8083"
  - name: ROUTES_ORDER
    value: "http://order-service:8084"
  - name: ROUTES_CART
    value: "http://cart-service:8081"

  # spring.application.name
  - name: SPRING_APPLICATION_NAME
    value: "api-gateway"

  # spring.cloud.gateway.routes[0] = courier-route
  - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
    value: "courier-route"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
    value: "http://courier-service:8082"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
    value: "Path=/couriers/**"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0
    value: "PrefixPath=/api"

  # spring.cloud.gateway.routes[1] = delivery-route
  - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
    value: "delivery-route"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
    value: "http://courier-service:8082"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
    value: "Path=/delivery-tasks/**"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_1_FILTERS_0
    value: "PrefixPath=/api"

  # spring.cloud.gateway.routes[2] = warehouse-route
  - name: SPRING_CLOUD_GATEWAY_ROUTES_2_ID
    value: "warehouse-route"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_2_URI
    value: "http://warehouse-service:8085"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0
    value: "Path=/warehouse/**"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_2_FILTERS_0
    value: "PrefixPath=/api"

  # spring.cloud.gateway.routes[3] = cart-route
  - name: SPRING_CLOUD_GATEWAY_ROUTES_3_ID
    value: "cart-route"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_3_URI
    value: "http://cart-service:8081"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_3_PREDICATES_0
    value: "Path=/carts/**"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_3_FILTERS_0
    value: "PrefixPath=/api"

  # spring.cloud.gateway.routes[4] = order-route
  - name: SPRING_CLOUD_GATEWAY_ROUTES_4_ID
    value: "order-route"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_4_URI
    value: "http://order-service:8084"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_4_PREDICATES_0
    value: "Path=/orders/**"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_4_FILTERS_0
    value: "PrefixPath=/api"

  # spring.cloud.gateway.routes[5] = user-route
  - name: SPRING_CLOUD_GATEWAY_ROUTES_5_ID
    value: "user-route"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_5_URI
    value: "http://auth-service:8086"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_5_PREDICATES_0
    value: "Path=/users/**"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_5_FILTERS_0
    value: "PrefixPath=/api"

  # spring.cloud.gateway.routes[6] = admin-route
  - name: SPRING_CLOUD_GATEWAY_ROUTES_6_ID
    value: "admin-route"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_6_URI
    value: "http://auth-service:8086"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_6_PREDICATES_0
    value: "Path=/admins/**"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_6_FILTERS_0
    value: "PrefixPath=/api"

  # spring.cloud.gateway.routes[7] = auth-route
  - name: SPRING_CLOUD_GATEWAY_ROUTES_7_ID
    value: "auth-route"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_7_URI
    value: "http://auth-service:8086"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_7_PREDICATES_0
    value: "Path=/auth/**"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_7_FILTERS_0
    value: "PrefixPath=/api"

logVolume:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 150m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 400Mi