serviceName: cart

replicaCount: 1

image:
  repository: your-registry/cart-backend # <-- REPLACE with your actual Auth service image location
  tag: v1.0.0

service:
  port: 8081
  type: ClusterIP

env:
  - name: SPRING_DATA_MONGODB_URI
    value: mongodb://mongo-db:27017/courierDB

secretName: cart-secrets

logVolume:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 150m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 400Mi
