
serviceName: grafana

replicaCount: 2

image:
  repository: grafana/grafana
  tag: 11.6.1

service:
  port: 3000
  type: ClusterIP

logVolume:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 150m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 400Mi