
serviceName: loki

replicaCount: 2

image:
  repository: grafana/loki
  tag: 3.5.0

command:
  - config.file=/etc/loki/local-config.yaml

service:
  port: 3100
  type: ClusterIP

logVolume:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 150m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 400Mi