
serviceName: mongo

replicaCount: 2

image:
  repository: mongo
  tag: 6.0

service:
  port: 27017
  type: ClusterIP

secretName: mongo-secrets

logVolume:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 150m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 400Mi