serviceName: promtail

replicaCount: 1

image:
  repository: grafana/promtail
  tag: 3.5.0

command:
  - -config.file=/etc/promtail/promtail-config.yaml

extraVolumes:
  - name: promtail-config
    hostPath:
      path: /absolute/path/to/promtail-config.yml
      type: File
  - name: logs
    hostPath:
      path: /absolute/path/to/logs
      type: Directory

extraVolumeMounts:
  - name: promtail-config
    mountPath: /etc/promtail/promtail-config.yaml
    subPath: promtail-config.yaml
  - name: logs
    mountPath: /logs

service:
  port: 9080
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi