
serviceName: psql

replicaCount: 4

image:
  repository: postgres
  tag: 14.17

service:
  port: 5432
  type: ClusterIP

secretName: psql-secrets

logVolume:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 150m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 400Mi