
serviceName: redis

replicaCount: 2

image:
  repository: redis
  tag: 7.4.3

service:
  port: 6379
  type: ClusterIP

logVolume:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 150m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 400Mi