
serviceName: warehouse

replicaCount: 1

image:
  repository: nourwk/warehouse
  tag: v1.0.0

service:
  port: 8085
  type: ClusterIP

env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://psql-db:5432/warehouseDB

secretName: warehouse-secrets
logVolume:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 150m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 400Mi