{{- if .Values.logVolume.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.serviceName }}-log-pvc
  labels:
    {{- include "spring-boot-microservice.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.logVolume.size }}
{{- end -}}
