apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-microservice.fullname" . }}-service
  labels:
    {{- include "spring-boot-microservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "spring-boot-microservice.selectorLabels" . | nindent 8 }}
