apiVersion: v1
kind: Service
metadata:
  name: mongo-courier-service
  namespace: dev
  labels:
    app: mongo-courier
spec:
  type: ClusterIP
  ports:
    - port: 27018
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app: mongo-courier