apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app.kubernetes.io/name: order
    app.kubernetes.io/instance: order-service # Using service name as instance name
    app.kubernetes.io/managed-by: manual # Indicating manual management
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: order
      app.kubernetes.io/instance: order-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order
        app.kubernetes.io/instance: order-service
    spec:
      containers:
        - name: order
          image: "nourwk/order:v1.0.5"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://psql-order-service:5434/$(ORDER_DB_NAME)
            - name: SPRING_RABBITMQ_HOST
              value: my-rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /api
            - name: SERVER_PORT
              value: "8084"
          envFrom:
            - secretRef:
                name: order-secrets
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8084
            initialDelaySeconds: 300
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8084
            initialDelaySeconds: 300
            periodSeconds: 30