apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/instance: auth-service # Using service name as instance name
    app.kubernetes.io/managed-by: manual # Indicating manual management
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
      app.kubernetes.io/instance: auth-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth
        app.kubernetes.io/instance: auth-service
    spec:
      containers:
        - name: auth
          image: "nourwk/auth:v1.0.2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://psql-auth-service:5432/$(AUTH_DB_NAME)
            - name: SPRING_DATA_REDIS_HOST
              value: redis-service
            - name: SERVER_PORT
              value: "8086"
          envFrom:
            - secretRef:
                name: auth-secrets
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8086
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8086
            initialDelaySeconds: 300
            periodSeconds: 5