apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-erp-pvc
  namespace: dev
  labels:
    app: psql-erp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi