apiVersion: v1
kind: Service
metadata:
  name: psql-erp-service
  namespace: dev
  labels:
    app: psql-erp
spec:
  type: ClusterIP
  ports:
    - port: 5433
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: psql-erp