apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-warehouse-pvc
  namespace: dev
  labels:
    app: psql-warehouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi