apiVersion: v1
kind: Service
metadata:
  name: psql-warehouse-service
  namespace: dev
  labels:
    app: psql-warehouse
spec:
  type: ClusterIP
  ports:
    - port: 5435
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: psql-warehouse