apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  labels:
    app.kubernetes.io/name: cart
    app.kubernetes.io/instance: cart-service # Using service name as instance name
    app.kubernetes.io/managed-by: manual # Indicating manual management
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cart
      app.kubernetes.io/instance: cart-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cart
        app.kubernetes.io/instance: cart-service
    spec:
      containers:
        - name: cart
          image: "ahmadhoseiny/cart:v1.1.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://$(SPRING_DATA_MONGODB_USERNAME):$(SPRING_DATA_MONGODB_PASSWORD)@mongo-cart-service:27017/$(CART_DB_NAME)?authSource=admin
            - name: SPRING_RABBITMQ_HOST
              value: my-rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /api
            - name: SERVER_PORT
              value: "8081"
          envFrom:
            - secretRef:
                name: cart-secrets
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8081
            initialDelaySeconds: 300
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8081
            initialDelaySeconds: 300
            periodSeconds: 30