apiVersion: v1
kind: Service
metadata:
  name: cart-service
  labels:
    app.kubernetes.io/name: cart
    app.kubernetes.io/instance: cart-service # Using service name as instance name
    app.kubernetes.io/managed-by: manual # Indicating manual management
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: cart
    app.kubernetes.io/instance: cart-service