apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/instance: auth-service # Using service name as instance name
    app.kubernetes.io/managed-by: manual # Indicating manual management
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: auth
    app.kubernetes.io/instance: auth-service