apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: user-analytics-courier-registered-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: user_exchange
  destination: analytics_user_event_queue
  destinationType: queue
  routingKey: courier.registered
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: user-analytics-customer-registered-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: user_exchange
  destination: analytics_user_event_queue
  destinationType: queue
  routingKey: customer.registered
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: inventory-analytics-product-created-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: inventory_exchange
  destination: analytics_inventory_event_queue
  destinationType: queue
  routingKey: product.created
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: inventory-analytics-inventory-updated-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: inventory_exchange
  destination: analytics_inventory_event_queue
  destinationType: queue
  routingKey: inventory.updated
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-analytics-cart-checkedout-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: order_exchange
  destination: analytics_order_event_queue
  destinationType: queue
  routingKey: cart.checkedout
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-analytics-order-star-binding # Using 'star' to represent '*'
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: order_exchange
  destination: analytics_order_event_queue
  destinationType: queue
  routingKey: order.*
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-order-cart-checkedout-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: order_exchange
  destination: order_order_event_queue
  destinationType: queue
  routingKey: cart.checkedout
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-order-packaged-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: order_exchange
  destination: order_order_event_queue
  destinationType: queue
  routingKey: order.packaged
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-order-shipped-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: order_exchange
  destination: order_order_event_queue
  destinationType: queue
  routingKey: order.shipped
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-order-delivered-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: order_exchange
  destination: order_order_event_queue
  destinationType: queue
  routingKey: order.delivered
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-order-failed-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: order_exchange
  destination: order_order_event_queue
  destinationType: queue
  routingKey: order.failed
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-warehouse-placed-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: order_exchange
  destination: warehouse_order_event_queue
  destinationType: queue
  routingKey: order.placed
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-warehouse-cancelled-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: order_exchange
  destination: warehouse_order_event_queue
  destinationType: queue
  routingKey: order.cancelled
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-warehouse-assigned-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: order_exchange
  destination: warehouse_order_event_queue
  destinationType: queue
  routingKey: order.assigned_to_courier
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-courier-packaged-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: order_exchange
  destination: courier_order_event_queue
  destinationType: queue
  routingKey: order.packaged
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-courier-assigned-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: order_exchange
  destination: courier_order_event_queue
  destinationType: queue
  routingKey: order.assigned_to_courier
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-courier-shipped-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: order_exchange
  destination: courier_order_event_queue
  destinationType: queue
  routingKey: order.shipped
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-courier-delivered-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: order_exchange
  destination: courier_order_event_queue
  destinationType: queue
  routingKey: order.delivered
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-courier-failed-binding
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  source: order_exchange
  destination: courier_order_event_queue
  destinationType: queue
  routingKey: order.failed
  vhost: /