apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-definitions
data:
  definitions.json: |
    {
      "exchanges": [
        { "name": "user_exchange", "vhost": "/", "type": "topic", "durable": true },
        { "name": "inventory_exchange", "vhost": "/", "type": "topic", "durable": true },
        { "name": "order_exchange", "vhost": "/", "type": "topic", "durable": true }
      ],
      "queues": [
        { "name": "analytics_user_event_queue", "vhost": "/", "durable": true },
        { "name": "analytics_order_event_queue", "vhost": "/", "durable": true },
        { "name": "analytics_inventory_event_queue", "vhost": "/", "durable": true },
        { "name": "order_order_event_queue", "vhost": "/", "durable": true },
        { "name": "warehouse_order_event_queue", "vhost": "/", "durable": true },
        { "name": "courier_order_event_queue", "vhost": "/", "durable": true }
      ],
      "bindings": [
        { "source": "user_exchange", "destination": "analytics_user_event_queue", "destination_type": "queue", "routing_key": "courier.registered" },
        { "source": "user_exchange", "destination": "analytics_user_event_queue", "destination_type": "queue", "routing_key": "customer.registered" },

        { "source": "inventory_exchange", "destination": "analytics_inventory_event_queue", "destination_type": "queue", "routing_key": "product.created" },
        { "source": "inventory_exchange", "destination": "analytics_inventory_event_queue", "destination_type": "queue", "routing_key": "inventory.updated" },

        { "source": "order_exchange", "destination": "analytics_order_event_queue", "destination_type": "queue", "routing_key": "cart.checkedout" },
        { "source": "order_exchange", "destination": "analytics_order_event_queue", "destination_type": "queue", "routing_key": "order.*" },

        { "source": "order_exchange", "destination": "order_order_event_queue", "destination_type": "queue", "routing_key": "cart.checkedout" },
        { "source": "order_exchange", "destination": "order_order_event_queue", "destination_type": "queue", "routing_key": "order.packaged" },
        { "source": "order_exchange", "destination": "order_order_event_queue", "destination_type": "queue", "routing_key": "order.shipped" },
        { "source": "order_exchange", "destination": "order_order_event_queue", "destination_type": "queue", "routing_key": "order.delivered" },
        { "source": "order_exchange", "destination": "order_order_event_queue", "destination_type": "queue", "routing_key": "order.failed" },

        { "source": "order_exchange", "destination": "warehouse_order_event_queue", "destination_type": "queue", "routing_key": "order.placed" },
        { "source": "order_exchange", "destination": "warehouse_order_event_queue", "destination_type": "queue", "routing_key": "order.cancelled" },
        { "source": "order_exchange", "destination": "warehouse_order_event_queue", "destination_type": "queue", "routing_key": "order.assigned_to_courier" },

        { "source": "order_exchange", "destination": "courier_order_event_queue", "destination_type": "queue", "routing_key": "order.packaged" },
        { "source": "order_exchange", "destination": "courier_order_event_queue", "destination_type": "queue", "routing_key": "order.assigned_to_courier" },
        { "source": "order_exchange", "destination": "courier_order_event_queue", "destination_type": "queue", "routing_key": "order.shipped" },
        { "source": "order_exchange", "destination": "courier_order_event_queue", "destination_type": "queue", "routing_key": "order.delivered" },
        { "source": "order_exchange", "destination": "courier_order_event_queue", "destination_type": "queue", "routing_key": "order.failed" }
      ]
    }
