apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: user-exchange
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  name: user_exchange
  vhost: /
  type: topic
  durable: true
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: inventory-exchange
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  name: inventory_exchange
  vhost: /
  type: topic
  durable: true
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: order-exchange
  namespace: dev
  labels:
    rabbitmq.com/cluster: my-rabbitmq
spec:
  name: order_exchange
  vhost: /
  type: topic
  durable: true