apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: my-rabbitmq
  namespace: dev
spec:
  secretBackend:
    externalSecret:
      name: rabbitmq-secrets
  replicas: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
  rabbitmq:
#    additionalConfig: |
#      load_definitions = /etc/rabbitmq-definitions/definitions.json
#      loopback_users.guest = false
    additionalPlugins:
      - rabbitmq_management
  override:
    statefulSet:
      spec:
        template:
          spec:
            volumes:
              - name: rabbitmq-definitions
                configMap:
                  name: rabbitmq-definitions
            containers:
              - name: rabbitmq
                volumeMounts:
                  - name: rabbitmq-definitions
                    mountPath: /etc/rabbitmq-definitions
                    readOnly: true
