apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: analytics-user-event-queue # Unique name for this CR
  namespace: dev # Must match your RabbitmqCluster namespace
spec:
  name: analytics_user_event_queue # The actual name of the queue in RabbitMQ
  vhost: / # The vhost name
  durable: true # Is durable?
  # autoDelete: false # Optional: defaults to false
  # arguments: {} # Optional: add queue arguments if needed
  # node: rabbit@my-rabbitmq-server-0 # Optional: Pin to a specific node (use caution)
  rabbitmqClusterReference:
    name: my-rabbitmq # Link to your RabbitmqCluster resource name
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: analytics-order-event-queue # Unique name for this CR
  namespace: dev # Must match your RabbitmqCluster namespace
spec:
  name: analytics_order_event_queue # The actual name of the queue in RabbitMQ
  vhost: / # The vhost name
  durable: true # Is durable?
  # autoDelete: false # Optional: defaults to false
  # arguments: {} # Optional: add queue arguments if needed
  # node: rabbit@my-rabbitmq-server-0 # Optional: Pin to a specific node (use caution)
  rabbitmqClusterReference:
    name: my-rabbitmq # Link to your RabbitmqCluster resource name
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: analytics-inventory-event-queue # Unique name for this CR
  namespace: dev # Must match your RabbitmqCluster namespace
spec:
  name: analytics_inventory_event_queue # The actual name of the queue in RabbitMQ
  vhost: / # The vhost name
  durable: true # Is durable?
  # autoDelete: false # Optional: defaults to false
  # arguments: {} # Optional: add queue arguments if needed
  # node: rabbit@my-rabbitmq-server-0 # Optional: Pin to a specific node (use caution)
  rabbitmqClusterReference:
    name: my-rabbitmq # Link to your RabbitmqCluster resource name
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: order-order-event-queue # Unique name for this CR
  namespace: dev # Must match your RabbitmqCluster namespace
spec:
  name: order_order_event_queue # The actual name of the queue in RabbitMQ
  vhost: / # The vhost name
  durable: true # Is durable?
  # autoDelete: false # Optional: defaults to false
  # arguments: {} # Optional: add queue arguments if needed
  # node: rabbit@my-rabbitmq-server-0 # Optional: Pin to a specific node (use caution)
  rabbitmqClusterReference:
    name: my-rabbitmq # Link to your RabbitmqCluster resource name
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: order-inventory-event-queue # Unique name for this CR
  namespace: dev # Must match your RabbitmqCluster namespace
spec:
  name: order_inventory_event_queue # The actual name of the queue in RabbitMQ
  vhost: / # The vhost name
  durable: true # Is durable?
  # autoDelete: false # Optional: defaults to false
  # arguments: {} # Optional: add queue arguments if needed
  # node: rabbit@my-rabbitmq-server-0 # Optional: Pin to a specific node (use caution)
  rabbitmqClusterReference:
      name: my-rabbitmq # Link to your RabbitmqCluster resource name
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: warehouse-order-event-queue # Unique name for this CR
  namespace: dev # Must match your RabbitmqCluster namespace
spec:
  name: warehouse_order_event_queue # The actual name of the queue in RabbitMQ
  vhost: / # The vhost name
  durable: true # Is durable?
  # autoDelete: false # Optional: defaults to false
  # arguments: {} # Optional: add queue arguments if needed
  # node: rabbit@my-rabbitmq-server-0 # Optional: Pin to a specific node (use caution)
  rabbitmqClusterReference:
    name: my-rabbitmq # Link to your RabbitmqCluster resource name
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: warehouse-inventory-event-queue # Unique name for this CR
  namespace: dev # Must match your RabbitmqCluster namespace
spec:
  name: warehouse_inventory_event_queue # The actual name of the queue in RabbitMQ
  vhost: / # The vhost name
  durable: true # Is durable?
  # autoDelete: false # Optional: defaults to false
  # arguments: {} # Optional: add queue arguments if needed
  # node: rabbit@my-rabbitmq-server-0 # Optional: Pin to a specific node (use caution)
  rabbitmqClusterReference:
      name: my-rabbitmq # Link to your RabbitmqCluster resource name
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: courier-user-event-queue # Unique name for this CR
  namespace: dev # Must match your RabbitmqCluster namespace
spec:
  name: courier_user_event_queue # The actual name of the queue in RabbitMQ
  vhost: / # The vhost name
  durable: true # Is durable?
  # autoDelete: false # Optional: defaults to false
  # arguments: {} # Optional: add queue arguments if needed
  # node: rabbit@my-rabbitmq-server-0 # Optional: Pin to a specific node (use caution)
  rabbitmqClusterReference:
      name: my-rabbitmq # Link to your RabbitmqCluster resource name
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: courier-order-event-queue # Unique name for this CR
  namespace: dev # Must match your RabbitmqCluster namespace
spec:
  name: courier_order_event_queue # The actual name of the queue in RabbitMQ
  vhost: / # The vhost name
  durable: true # Is durable?
  # autoDelete: false # Optional: defaults to false
  # arguments: {} # Optional: add queue arguments if needed
  # node: rabbit@my-rabbitmq-server-0 # Optional: Pin to a specific node (use caution)
  rabbitmqClusterReference:
    name: my-rabbitmq # Link to your RabbitmqCluster resource name
