apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-scripts
  namespace: dev
data:
  init-users-mongo.sh: |
    #!/bin/bash
    mongo <<EOF
    use $CART_MONGO_DB
    db.createUser({user: "$CART_MONGO_USERNAME", pwd: "$CART_MONGO_PASSWORD", roles: [{role: "readWrite", db: "$CART_MONGO_DB"}]})
    use $COURIER_MONGO_DB
    db.createUser({user: "$COURIER_MONGO_USERNAME", pwd: "$COURIER_MONGO_PASSWORD", roles: [{role: "readWrite", db: "$COURIER_MONGO_DB"}]})
    EOF