apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: dev
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:8.0.9
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongo-secrets
          volumeMounts:
            - name: data
              mountPath: /data/db
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 400Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongo-pvc